[theme]
primaryColor = "#3b82f6"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#f1f3f6"
textColor = "#1e272e"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false

